version: '3'
services:
  server-todo:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres